services:
  dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ..:/workspace
      - node_modules:/workspace/node_modules # volume trick
      - backend_node_modules:/workspace/backend/node_modules # volume trick

volumes:
  node_modules:
  backend_node_modules:
